### ISSUE TITLE
Can't add loot crate + Error.

### ISSUE THREAD

**Issue by MithrandirCraft** [SubSide/KOTH#101]
I attempt at adding a loot crate on a koth, but I get an internal error.
https://hastebin.com/venodomuna.vbs
Version is included on error. Spigot for mc 1.12.1

**Comment by SubSide** [comment]
Try updating to the latest version. This seems to be an issue that is caused by java itself and re-downloading the jar and installing it should fix the issue.

**Comment by SubSide** [comment]
This should be fixed in the next version!
Sorry for taking so long! :(

**Comment by MithrandirCraft** [comment]
Hi. I'm using 1.5.0b and I still can't establish a chest location for one of my koth.
https://hastebin.com/uzohijuwah.vbs

**Comment by SubSide** [comment]
Next version will be released somewhere today which should fix it 😊

**Comment by SubSide** [comment]
It was fixed with this commit:
45756925aa63185d9d219891808ec8444554d8d5

**Comment by MithrandirCraft** [comment]
Fixed.
